- name: Check if bash config file exists
  become: false
  stat:
    path: "{{ playbook_dir }}/files/bash/.bashrc"
  register: bashrc_file

- name: Restore bash config
  become: false
  copy:
    src: files/bash/.bashrc
    dest: /home/juniorsems/.bashrc
    owner: juniorsems
    group: juniorsems
    mode: '0644'
  when: bashrc_file.stat.exists
