- name: Ensure Flathub remote is added
  become: true
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install Flatpak apps
  become: true
  flatpak:
    name: "{{ flatpak_apps }}"
    state: present
  ignore_errors: true
